export default [
  {
    id: 1,
    name: "Barnil Sarma",
    email: "barnilsarma@gmail.com",
    address: "Guwahati, Assam",
    skills: ["JavaScript", "React", "Node.js"],
    experience: "1 year",
    appliedJobs: [1, 2],
  },
  {
    id: 2,
    name: "Ananya",
    email: "ananya@gmail.com",
    address: "West Bengal",
    skills: ["Python", "Django", "PostgreSQL"],
    experience: "2 years",
    appliedJobs: [5, 12, 18],
  },
  {
    id: 3,
    name: "Rahul Sharma",
    email: "rahul.sharma@gmail.com",
    address: "Delhi, India",
    skills: ["Java", "Spring Boot", "MySQL"],
    experience: "3 years",
    appliedJobs: [7, 15],
  },
  {
    id: 4,
    name: "Priya Sen",
    email: "priya.sen@gmail.com",
    address: "Mumbai, Maharashtra",
    skills: ["HTML", "CSS", "JavaScript"],
    experience: "1 year",
    appliedJobs: [10, 23, 31],
  },
  {
    id: 5,
    name: "Amit Verma",
    email: "amit.verma@gmail.com",
    address: "Lucknow, UP",
    skills: ["C++", "DSA", "Algorithms"],
    experience: "2 years",
    appliedJobs: [4, 19, 25],
  },
  {
    id: 6,
    name: "Neha Gupta",
    email: "neha.gupta@gmail.com",
    address: "Jaipur, Rajasthan",
    skills: ["React", "Next.js", "Firebase"],
    experience: "1 year",
    appliedJobs: [8, 20, 37],
  },
  {
    id: 7,
    name: "Rohit Kumar",
    email: "rohit.kumar@gmail.com",
    address: "Patna, Bihar",
    skills: ["Node.js", "Express", "MongoDB"],
    experience: "2 years",
    appliedJobs: [2, 16, 27],
  },
  {
    id: 8,
    name: "Sneha Roy",
    email: "sneha.roy@gmail.com",
    address: "Shillong, Meghalaya",
    skills: ["Python", "Flask", "SQLite"],
    experience: "1 year",
    appliedJobs: [6, 13, 34],
  },
  {
    id: 9,
    name: "Arjun Mehta",
    email: "arjun.mehta@gmail.com",
    address: "Chandigarh, India",
    skills: ["Angular", "TypeScript", "RxJS"],
    experience: "3 years",
    appliedJobs: [9, 24, 30],
  },
  {
    id: 10,
    name: "Riya Singh",
    email: "riya.singh@gmail.com",
    address: "Bhopal, MP",
    skills: ["Kotlin", "Android", "Firebase"],
    experience: "2 years",
    appliedJobs: [1, 17, 28],
  },
  {
    id: 11,
    name: "Aditya Jain",
    email: "aditya.jain@gmail.com",
    address: "Hyderabad, Telangana",
    skills: ["Go", "Microservices", "Docker"],
    experience: "4 years",
    appliedJobs: [11, 29, 36],
  },
  {
    id: 12,
    name: "Kavya Iyer",
    email: "kavya.iyer@gmail.com",
    address: "Chennai, Tamil Nadu",
    skills: ["JavaScript", "Vue.js", "Pinia"],
    experience: "2 years",
    appliedJobs: [14, 21, 33],
  },
  {
    id: 13,
    name: "Manish Patel",
    email: "manish.patel@gmail.com",
    address: "Ahmedabad, Gujarat",
    skills: ["PHP", "Laravel", "MySQL"],
    experience: "3 years",
    appliedJobs: [3, 18, 26],
  },
  {
    id: 14,
    name: "Pooja Nair",
    email: "pooja.nair@gmail.com",
    address: "Thiruvananthapuram, Kerala",
    skills: ["Swift", "iOS", "CoreData"],
    experience: "2 years",
    appliedJobs: [7, 22, 35],
  },
  {
    id: 15,
    name: "Vikram Reddy",
    email: "vikram.reddy@gmail.com",
    address: "Visakhapatnam, AP",
    skills: ["Rust", "Systems Programming", "WASM"],
    experience: "3 years",
    appliedJobs: [12, 20, 39],
  },
  {
    id: 16,
    name: "Meera Kapoor",
    email: "meera.kapoor@gmail.com",
    address: "Pune, Maharashtra",
    skills: ["Data Science", "Python", "TensorFlow"],
    experience: "2 years",
    appliedJobs: [6, 25, 32],
  },
  {
    id: 17,
    name: "Sanjay Malhotra",
    email: "sanjay.malhotra@gmail.com",
    address: "Delhi, India",
    skills: ["C#", ".NET", "Azure"],
    experience: "5 years",
    appliedJobs: [13, 27, 40],
  },
  {
    id: 18,
    name: "Ankita Bose",
    email: "ankita.bose@gmail.com",
    address: "Kolkata, West Bengal",
    skills: ["UI/UX", "Figma", "Adobe XD"],
    experience: "1 year",
    appliedJobs: [5, 19, 38],
  },
  {
    id: 19,
    name: "Harsh Vardhan",
    email: "harsh.vardhan@gmail.com",
    address: "Ranchi, Jharkhand",
    skills: ["Cybersecurity", "Networking", "Linux"],
    experience: "4 years",
    appliedJobs: [15, 28, 31],
  },
  {
    id: 20,
    name: "Divya Mishra",
    email: "divya.mishra@gmail.com",
    address: "Nagpur, Maharashtra",
    skills: ["Cloud", "AWS", "DevOps"],
    experience: "3 years",
    appliedJobs: [2, 23, 29],
  },
];
